### ISSUE TITLE
Add creation of campaigns

### ISSUE THREAD

**Issue by vsimetka** [Giveth/milestonetracker-ui#13]
Implement campaign creation in the DAPP. The process should also offer creating or linking following contracts:

- Vault contract
- Token contract
- Milestone tracker contract

**Comment by GriffGreen** [comment]
This will be a long discussion... but I will kick it off.

After a good convo with Vojtech, I think a genesis MM token and vault token should be generated for every new "tag"  this can probably be a lower priority for now until we start working on the donation side of things and design that work flow. 

**More pertinent is the creation of Campaigns directly on the UI.**

Since the Milestone Trackers are limited by blocksize... I would like to start breaking up Giveth into multiple Campaigns: Smart Contract Development, Frontend/UI, Community, Brand Management, expenses, etc.

I would love to do this with the UI!

So that a user (ahem, me) Can become a CampaignDirector (Formerly Recipient) when they deploy a Campaign. 

During the Deployment, they 
1. name the Campaign and set all the other required variables
2. request being an allowedspender on a specific vault
3. request being added to the directory
4. set defaults for certain values as mentioned in https://github.com/Giveth/milestonetracker-ui/issues/14#issuecomment-284343164
5. Set a dedicated communication channel for that campaign
6. I'm sure lots of other things ;-)
