### ISSUE TITLE
Blockchain status

### ISSUE THREAD

**Issue by vsimetka** [Giveth/milestonetracker-ui#9]
Show the status of the blockchain. At minimum user needs to know if the chain is up to date, updating or disconnected. To be discussed if there is a value in showing anything else like how far behind the user is, what is the current block etc...

**Comment by GriffGreen** [comment]
The easiest way to do this is to post the current block and the time since the last block at the top of the page, if the time is more than 45 minutes, you can change the time to "Your blockchain is out of date"

At least... this is how other apps do it.

NOTE: I say 45 Minutes because during the Shanghai Hacks, the blockchain stopped for 30+ minutes...
